// <auto-generated />
using System;
using EntertenimentManager.Infra.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntertenimentManager.Infra.Migrations
{
    [DbContext(typeof(EntertenimentManagementDataContext))]
    partial class EntertenimentManagementDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EntertenimentManager.Domain.Entities.Categories.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("EntertenimentManager.Domain.Entities.Itens.Contracts.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BelongsToId")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlImage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BelongsToId");

                    b.ToTable("Item");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("EntertenimentManager.Domain.Entities.Itens.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("Id");

                    b.ToTable("Platform", (string)null);
                });

            modelBuilder.Entity("EntertenimentManager.Domain.Entities.Lists.PersonalList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("PersonalList", (string)null);
                });

            modelBuilder.Entity("EntertenimentManager.Domain.Entities.Users.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("Id");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("EntertenimentManager.Domain.Entities.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "IX_User_Email")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("GamePlatforms", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("PlatformsId")
                        .HasColumnType("int");

                    b.HasKey("GameId", "PlatformsId");

                    b.HasIndex("PlatformsId");

                    b.ToTable("GamePlatforms");
                });

            modelBuilder.Entity("UserRoles", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("EntertenimentManager.Domain.Entities.Itens.Game", b =>
                {
                    b.HasBaseType("EntertenimentManager.Domain.Entities.Itens.Contracts.Item");

                    b.Property<string>("Developer")
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR");

                    b.ToTable("Game", (string)null);
                });

            modelBuilder.Entity("EntertenimentManager.Domain.Entities.Itens.Movie", b =>
                {
                    b.HasBaseType("EntertenimentManager.Domain.Entities.Itens.Contracts.Item");

                    b.Property<string>("Director")
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("Distributor")
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("int");

                    b.ToTable("Movie", (string)null);
                });

            modelBuilder.Entity("EntertenimentManager.Domain.Entities.Categories.Category", b =>
                {
                    b.HasOne("EntertenimentManager.Domain.Entities.Users.User", "Owner")
                        .WithMany("Categories")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .HasConstraintName("FK_Category_Owner");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("EntertenimentManager.Domain.Entities.Itens.Contracts.Item", b =>
                {
                    b.HasOne("EntertenimentManager.Domain.Entities.Lists.PersonalList", "BelongsTo")
                        .WithMany("Items")
                        .HasForeignKey("BelongsToId");

                    b.Navigation("BelongsTo");
                });

            modelBuilder.Entity("EntertenimentManager.Domain.Entities.Lists.PersonalList", b =>
                {
                    b.HasOne("EntertenimentManager.Domain.Entities.Categories.Category", "Category")
                        .WithMany("Lists")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .HasConstraintName("FK_PersonalList_Category");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("GamePlatforms", b =>
                {
                    b.HasOne("EntertenimentManager.Domain.Entities.Itens.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GamePlatforms_PlatformId");

                    b.HasOne("EntertenimentManager.Domain.Entities.Itens.Platform", null)
                        .WithMany()
                        .HasForeignKey("PlatformsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GamePlatforms_GameId");
                });

            modelBuilder.Entity("UserRoles", b =>
                {
                    b.HasOne("EntertenimentManager.Domain.Entities.Users.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_UserId");

                    b.HasOne("EntertenimentManager.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_RoleId");
                });

            modelBuilder.Entity("EntertenimentManager.Domain.Entities.Itens.Game", b =>
                {
                    b.HasOne("EntertenimentManager.Domain.Entities.Itens.Contracts.Item", null)
                        .WithOne()
                        .HasForeignKey("EntertenimentManager.Domain.Entities.Itens.Game", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EntertenimentManager.Domain.Entities.Itens.Movie", b =>
                {
                    b.HasOne("EntertenimentManager.Domain.Entities.Itens.Contracts.Item", null)
                        .WithOne()
                        .HasForeignKey("EntertenimentManager.Domain.Entities.Itens.Movie", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EntertenimentManager.Domain.Entities.Categories.Category", b =>
                {
                    b.Navigation("Lists");
                });

            modelBuilder.Entity("EntertenimentManager.Domain.Entities.Lists.PersonalList", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("EntertenimentManager.Domain.Entities.Users.User", b =>
                {
                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
